name: Sync multiple branches
on:
  push:
    branches:
      - 'master'
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge master -> preprod
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: master
          target_branch: preprod
          github_token: ${{ github.token }}